class Hero():  # --> Employee inherits the pyDatalog capability

    def __init__(self, name, range, type,  ability, difficulty, tier):
        # call the initialization method of the Mixin class
        self.name = name
        self.range = range
        self.type = type
        self.difficulty = difficulty
        self.ability = ability
        self.tier = tier

    def __repr__(self):  # specifies how to display
        return self.name





def generateList():
		#              name      range     type           ability                      difficulty tier
	abaddon = Hero('abaddon', 'Melee', 'Strength', ['Dispel','Healing','Durable'],  1, 4)
	alchemist = Hero('alchemist', 'Melee', 'Strength', ['Healing','Physical','Carry','Farm'],  1, 1)
	axe = Hero('axe', 'Melee', 'Strength', ['Disabler','Initiator','Durable'],  1, 1)
	beastmaster = Hero('beastmaster', 'Melee', 'Strength',    ['Vision','Pusher','Summoner','Disabler', 'Initiator','Durable', 'Nuker'],  1, 1)
	brewmaster = Hero('brewmaster','Melee','Strength',['Carry', 'Ganker', 'Durabler' ,'Initiator','Disable','Nuker'],3,1)
	bristleback = Hero('bristleback', 'Melee', 'Strength',    ['Durable','Ganker','Damage-Increase'],  1, 1)
	centaur = Hero('centaur', 'Melee', 'Strength', ['Durable','Initiator','Disabler'],  1, 1)
	chaos_knight = Hero('chaos_knight', 'Melee', 'Strength',    ['Carry','Disabler' , 'Durable' , 'Pusher' , 'Initiator','Phantom'],  1, 1)
	rattletrap = Hero('rattletrap', 'Melee', 'Strength',    ['Initiator', 'Disabler', 'Durable', 'Nuker'],  1, 1)
	doom_bringer = Hero('doom_bringer', 'Melee', 'Strength',    ['Silencer','Carry', 'Disabler', 'Initiator', 'Durable', 'Nuker'],  1, 1)
	dragon_knight = Hero('dragon_knight', 'Melee', 'Strength',    ['Carry' , 'Pusher' ,'Durable' , 'Disabler' , 'Initiator' , 'Nuker'],  1, 1)
	earth_spirit = Hero('earth_spirit', 'Melee', 'Strength',    ['Nuker' , 'Escape' , 'Disabler' , 'Initiator' , 'Durable'],  1, 1)
	earthshaker = Hero('earthshaker', 'Melee', 'Strength',    ['Support' , 'Initiator', 'Disabler', 'Nuker'],  1, 1)
	elder_titan = Hero('elder_titan', 'Melee', 'Strength',    ['Disabler','Initiator','Durable','Nuker'],  1, 1)
	huskar = Hero('huskar', 'Melee', 'Strength',    ['Carry' ,'Durable', 'Initiator','Healing','Nausty'],  1, 1)
	wisp = Hero('wisp', 'Melee', 'Strength',    ['Support' ,'Escape' , 'Nuker'],  1, 1)
	kunkka = Hero('kunkka', 'Melee', 'Strength',    ['Split','Carry' ,'Support' ,'Disabler' ,'Initiator' ,'Durable' ,'Nuker'],  1, 1)
	legion_commander = Hero('legion_commander', 'Melee', 'Strength',    ['Carry', 'Disabler', 'Initiator', 'Durable', 'Nuker'],  1, 1)
	life_stealer = Hero('life_stealer', 'Melee', 'Strength',    ['Carry' ,'Durable' ,'Jungler' ,'Escape' ,'Disabler', 'Dispel', 'Healing','Squishy'],  1, 1)
	lycan = Hero('lycan', 'Melee', 'Strength',    ['Carry', 'Pusher', 'Jungler', 'Durable', 'Escape'],  1, 1)
	magnataur = Hero('magnataur', 'Melee', 'Strength',    ['Initiator', 'Disabler', 'Nuker', 'Escape'],  1, 1)
	mars = Hero('mars', 'Melee', 'Strength',    ['Carry' , 'Initiator', 'Disabler',  'Durable'],  1, 1)
	night_stalker = Hero('night_stalker', 'Melee', 'Strength',    ['Carry' ,'Initiator', 'Durable' , 'Disabler' , 'Nuker'],  1, 1)
	omniknight = Hero('omniknight', 'Melee', 'Strength',    ['Support', 'Durable', 'Nuker', 'Healing', 'Physical-Immunity'],  1, 1)
	phoenix = Hero('phoenix', 'Ranged', 'Strength',    ['Support', 'Nuker', 'Initiator', 'Escape', 'Disabler'],  1, 1)
	pudge = Hero('pudge', 'Melee', 'Strength',    ['Disabler' , 'Initiator' , 'Durable', 'Nuker'],  1, 1)
	sand_king = Hero('sand_king', 'Melee', 'Strength',    ['Suppress','Initiator' , 'Disabler' , 'Support' , 'Nuker' , 'Escape' , 'Jungler'],  1, 1)
	slardar = Hero('slardar', 'Melee', 'Strength',    ['Continued-Stun','Carry' , 'Durable' , 'Initiator' , 'Disabler' ,'Escape'],  1, 1)
	spirit_breaker = Hero('spirit_breaker', 'Melee', 'Strength',    ['Carry' , 'Initiator' , 'Disabler' , 'Durable', 'Escape'],  1, 1)
	SV = Hero('SV', 'Melee', 'Strength',    ['Split','Carry', 'Disabler', 'Initiator', 'Durable', 'Nuker'],  1, 1)
	tidehunter = Hero('tidehunter', 'Melee', 'Strength',    ['Initiator', 'Durable' , 'Disable' , 'Nuker'],  1, 1)
	timbersaw = Hero('timbersaw', 'Melee', 'Strength',    ['Nuker', 'Durable' , 'Escape'],  1, 1)
	tiny = Hero('tiny', 'Melee', 'Strength',    ['Carry', 'Disabler', 'Initiator', 'Durable', 'Nuker'],  1, 1)
	treant = Hero('treant', 'Melee', 'Strength',    ['Support' , 'Initiator' , 'Durable', 'Disabler','Escape'],  1, 1)
	tusk = Hero('tusk', 'Melee', 'Strength',    ['Carry', 'Disabler', 'Initiator', 'Durable', 'Nuker'],  1, 1)
	abyssal_underlord = Hero('Abyssal_Underlord', 'Melee', 'Strength',    ['Carry', 'Disabler', 'Initiator', 'Durable', 'Nuker'],  1, 1)
	undying = Hero('undying', 'Melee', 'Strength',    ['Steal_strength','Carry', 'Disabler', 'Initiator', 'Durable', 'Nuker'],  1, 1)
	skeleton_king = Hero('skeleton_king', 'Melee', 'Strength',    ['Carry', 'Disabler', 'Initiator', 'Durable', 'Nuker'],  1, 1)



	antimage= Hero('antimage', 'Ranged','Agility', ['Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	arc_warden= Hero('arc_warden', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	bloodseeker= Hero('bloodseeker', 'Melee','Agility', ['Anti-dispel','Silencer','Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	bounty_hunter= Hero('bounty_hunter', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	broodmother= Hero('broodmother', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	clinkz= Hero('clinkz', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	drow_ranger= Hero('drow_ranger', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	ember_spirit= Hero('ember_spirit', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	faceless_void= Hero('faceless_void', 'Ranged','Agility', ['Continued-Stun','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	gyrocopter= Hero('gyrocopter', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	juggernaut= Hero('juggernaut', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	lone_druid= Hero('lone_druid', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	luna= Hero('luna', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	medusa= Hero('medusa', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	meepo= Hero('meepo', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	mirana= Hero('mirana', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	monkey_king= Hero('monkey_king', 'Ranged','Agility', ['Phantom','Durable','Carry','Late','Mobility','Attribute-dependent','Invisable'], 1, 1)
	naga_siren= Hero('naga_siren', 'Ranged','Agility', ['Phantom','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	nyx_assassin= Hero('nyx_assassin', 'Ranged','Agility', ['Suppress','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	pangolier= Hero('pangolier', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	phantom_assassin= Hero('phantom_assassin', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	phantom_lancer= Hero('phantom_lancer', 'Ranged','Agility', ['Phantom','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	razor= Hero('razor', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	riki= Hero('riki', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	nevermore= Hero('nevermore', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	slark= Hero('slark', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	sniper= Hero('sniper', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	spectre= Hero('spectre', 'Ranged','Agility', ['Phantom','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	templar_assassin= Hero('templar_assassin', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	terrorblade= Hero('terrorblade', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	troll_warlord= Hero('troll_warlord', 'Changable','Agility', ['Continued-Stun','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	ursa= Hero('ursa', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	vengefulspirit= Hero('vengefulspirit', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	venomancer= Hero('venomancer', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	viper= Hero('viper', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	weaverspectre= Hero('weaverspectre', 'Ranged','Agility', ['Healing','Durable','Carry','Late','Mobility','Attribute-dependent'], 1, 1)
	morphling= Hero('morphling', 'Ranged','Agility', ['Healing','Durable','Carry','Transform','Late','Mobility','Attribute-dependent'], 1, 1)

	ancient_apparition = Hero('ancient_apparition', 'Ranged','Intelligence',['Support', 'Early', 'Anti-healing'],  1, 3)
	bane = Hero('bane', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	batrider = Hero('batrider', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	Chen = Hero('chen', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	crystal_maiden = Hero('crystal_maiden', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	dark_seer = Hero('dark_seer', 'Ranged','Intelligence',['Anti-dispel','Support', 'Early'],  1, 3)
	dark_willow = Hero('dark_willow', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	dazzle = Hero('dazzle', 'ranged','Intelligence',['Support', 'Early','Healing','Grave'],  1, 3)
	death_prophet = Hero('death_prophet', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	disruptor = Hero('disruptor', 'ranged','Intelligence',['Support', 'Early'],  1, 3)
	enchantress = Hero('enchantress', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	enigma = Hero('enigma', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	grimstroke = Hero('grimstroke', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	invoker = Hero('invoker', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	jakiro = Hero('jakiro', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	keeper_of_the_light = Hero('keeper_of_the_light', 'Ranged','Intelligence',['Lost_mana','Burst', 'AOE'],  1, 3)
	leshrac = Hero('leshrac', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	lich = Hero('lich', 'Ranged','Intelligence',['Burst','Nuker','Disabler'],  1, 3)
	lina = Hero('lina', 'Ranged','Intelligence',['Burst','Nuker','Early','Disabler','Suppress'], 1, 3)
	lion = Hero('lion', 'Ranged','Intelligence',['Burst','Nuker','Disabler','Support','Initiator'],  1, 3)
	furion = Hero('furion', 'Ranged','Intelligence',['Support', 'Summoner'],  1, 3)
	necrolyte = Hero('necrolyte', 'Ranged','Intelligence',['Support', 'Early', 'Healing'],  1, 3)
	ogre_magi = Hero('ogre_magi', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	oracle = Hero('oracle', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	obsidian_destroyer = Hero('obsidian_destroyer', 'Ranged','Intelligence',['Disable','Anti-dispel','Support', 'Early'],  1, 3)
	puck = Hero('puck', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	pugna = Hero('pugna', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	queenofpain = Hero('queenofpain', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	rubick = Hero('rubick', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	shadow_demon = Hero('shadow_demon', 'Ranged','Intelligence',['Support'],  1, 3)
	shadow_shaman = Hero('shadow_shaman', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	silencer = Hero('silencer', 'Ranged','Intelligence',['Support', 'Early','Silencer'],  1, 3)
	skywrath_mage = Hero('skywrath_mage', 'Ranged','Intelligence',['Support'],  1, 3)
	storm_spirit = Hero('storm_sirit', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	techies = Hero('techies', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	tinker = Hero('tTinker', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	visage = Hero('visage', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	warlock = Hero('warlock', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	windrunner = Hero('windrunner', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	winter_wyvern = Hero('winter_wyvern', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	witch_doctor = Hero('witch_doctor', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	zuus = Hero('zuus', 'Ranged','Intelligence',['Support', 'Early'],  1, 3)
	return locals()


